# Generated by Django 2.2.16 on 2020-10-07 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_demo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Demo",
        ),
    ]
