# Generated by Django 2.2.16 on 2020-10-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_hello_student"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Hello",
        ),
    ]
