# Generated by Django 2.2.16 on 2020-10-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_hello'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlessdf', models.BigIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Crowdbotic',
        ),
    ]
